--3 Pontos Positivos para usar View

--1 REUSO DO CÓDIGO - Através de Views podemos utilizar a consulta quantas vezes quisermos sem precisar 
--escrever o código novamente.

--2 SEGURANÇA - Através de Views podemos disponibilizar as informações somente dos campos que queremos

--3 SIMPLIFICAR - Aumentamos a produtividade reutilizando a consulta sempre que quisermos


--CRIANDO UMA VIEW  DE TODAS AS VENDAS
IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'VW_VENDAS_CLIENTES_GERAL' AND TYPE = 'V')
	BEGIN
		DROP VIEW VW_VENDAS_CLIENTES_GERAL
	END
GO

CREATE VIEW VW_VENDAS_CLIENTES_GERAL AS
SELECT
A.ID_VENDA,
A.DATA_VENDA,
A.QUANTIDADE,
B.VALOR AS VALOR_UNITARIO,
A.VALOR_TOTAL AS TOTAL_VENDA,
B.DESCRICAO AS PRODUTO,
C.NOME AS CLIENTE
FROM VENDAS A(NOLOCK)
INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)
INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)
GO



--UTILIZANDO A VIEW
SELECT * FROM VW_VENDAS_CLIENTES_GERAL



--CRIANDO UMA VIEW SOMENTE DE VENDAS COM VALORES SUPERIORES A 10.00 REAIS
IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'VW_VENDAS_CLIENTES_VALOR_MAIOR_10' AND TYPE = 'V')
	BEGIN
		DROP VIEW VW_VENDAS_CLIENTES_VALOR_MAIOR_10
	END
GO

CREATE VIEW VW_VENDAS_CLIENTES_VALOR_MAIOR_10 AS
SELECT
A.ID_VENDA,
A.DATA_VENDA,
A.QUANTIDADE,
B.VALOR AS VALOR_UNITARIO,
A.VALOR_TOTAL AS TOTAL_VENDA,
B.DESCRICAO AS PRODUTO,
C.NOME AS CLIENTE
FROM VENDAS A(NOLOCK)
INNER JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_PRODUTO)
INNER JOIN CLIENTES C(NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)
WHERE A.VALOR_TOTAL > 10
GO

--UTILIZANDO A VIEW
SELECT * FROM VW_VENDAS_CLIENTES_VALOR_MAIOR_10